stages:
  - build

build-script:
  stage: build
  tags: [jlselogin3_shell]
  script:
    - module load intel
    - git submodule update --init
    - ./autogen.pl
    - ./configure --prefix=$PWD/install_test
    - make install
    - make check
    - export PATH=$PWD/install_test/bin:$PATH
    - cd examples 
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - pwd
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-q iris"
    JLSE_IRIS_SCHEDULER_PARAMETERS: "-t 1:00:00 -n 1"
