stages:
  - build
  - test

build:
  stage: build
  tags: [jlselogin3_shell]
  script:
    - module load intel
    - git submodule update --init
    - ./autogen.pl
    - ./configure CC=icc FC=ifort CXX=icpc --prefix=$PWD/install_test --with-libevent=internal
    - make install
    - make check
    - export PATH=$PWD/install_test/bin:$PATH
    - cd examples 
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples
      - install_test

test:
  stage: test
  tags: 
    - jlselogin3_batch-03
  dependencies:
    - build
  script:
    - pwd
    - ls
    - module load intel
    - export PATH=$PWD/install_test/bin:$PATH
    - which mpirun
    - cd examples
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-qiris -t 1:00:00 -n 1"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
