stages:
  - build
  - test

.build-script:
  stage: build
  tags: [jlse]
  script:
    - module load intel
    - ./autogen.pl
    - ./configure --prefix=$PWD/install_test
    - make install
    - make check
    - cd examples 
    - make clean && make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - pwd

.test-script:
  stage: test
  tags: [jlse]
  script:
    - pwd
    - export PATH=$PwD/install_test/bin:$PATH
    - cd examples
    - mpirun  -np 4 ./hello_c


