variables:
  SCHEDULER_PARAMETERS: "-pskylake-gold -t 1:00:00 -N 1 --ntasks-per-node=16"
  GIT_STRATEGY: clone
  NPROCS: 4

stages:
  - build
  - test

.report-status:
  variables:
    # You can define ALL BUILDSTATUS_ variables here, with the
    # exception of the TOKEN if it makes it easier to manage.
    BUILDSTATUS_OWNER: hppritcha
    BUILDSTATUS_PROJECT: ompi
    BUILDSTATUS_APIURL: https://api.github.com
    BUILDSTATUS_JOB: LANL
  script:
    # ls -l /ccsopen/home/tjn3/ums/ompix/scripts/build-status.py
    - export BUILDSTATUS_OWNER=hppritcha
    - export BUILDSTATUS_PROJECT=ompi
    - export BUILDSTATUS_APIURL=https://api.github.com
    - export BUILDSTATUS_JOB=LANL
    - env | grep CI_
    - echo "DBG Running python build-status.py script"
    - python /home/hpp/bin/build-status.py
  dependencies: []
  cache:
    key: python-requests
    paths:
      - $CI_PROJECT_DIR/env/
    policy: pull

build:intel:
  stage: build
  tags: [darwin-slurm-shared]
  script:
    - module load intel
    - git submodule update --init
    - ./autogen.pl
    - ./configure CC=icc FC=ifort CXX=icpc --prefix=$PWD/install_test --with-libevent=internal
    - make -j 8 install
    - make check
    - export PATH=$PWD/install_test/bin:$PATH
    - cd examples 
    - make
  variables:
    SCHEDULER_PARAMETERS: "-pskylake-gold -t 1:00:00 -N 1 --ntasks-per-node=16"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples
      - install_test
    expire_in: 1 week

build:gnu:
  stage: build
  tags: [darwin-slurm-shared]
  script:
    - module load gcc
    - git submodule update --init
    - ./autogen.pl
    - ./configure --prefix=$PWD/install_test --with-libevent=internal
    - make -j 8 install
    - make check
    - export PATH=$PWD/install_test/bin:$PATH
    - cd examples 
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples
      - install_test
    expire_in: 1 week

test:intel:
  stage: test
  tags: [darwin-slurm-shared]
  dependencies:
    - build:intel
  needs: ["build:intel"]
  script:
    - pwd
    - ls
    - module load intel
    - export PATH=$PWD/install_test/bin:$PATH
    - which mpirun
    - cd examples
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 week

test:gnu:
  stage: test
  tags: [dawrin-slurm-shared]
  dependencies:
    - build:gnu
  needs: ["build:gnu"]
  script:
    - pwd
    - ls
    - module load gcc
    - export PATH=$PWD/install_test/bin:$PATH
    - which mpirun
    - cd examples
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 week

