stages:
  - build

build-script:
  stage: build
  tags: [jlse]
  script:
    - module load intel
    - ./autogen.pl
    - ./configure --prefix=$PWD/install_test
    - make install
    - make check
    - cd examples 
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - pwd
