name: GitHub Action CI

on: [pull_request]

env:
  ROCM_VER: 5-4
  MPI4PY_VERSION: 3.1.5
jobs:
  mpi4py:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends wget lsb-core software-properties-common curl python3-pip
        pip3 install cython
    - uses: actions/checkout@v3
      with:
            submodules: recursive
    - name: Build Open MPI
      run: |
        ./autogen.pl
        ./configure --prefix=${GITHUB_WORKSPACE}/install --disable-oshmem --disable-mpi-fortran
        make -j install
    - name: Build MPI4py
      run: |
        wget https://github.com/mpi4py/mpi4py/releases/download/${MPI4PY_VERSION}/mpi4py-3.1.5.tar.gz
        tar -zxf mpi4py-${MPI4PY_VERSION}.tar.gz
        echo "PYTHONPATH=${GITHUB_WORKSPACE}/mpi4py-${MPI4PY_VERSION}/" >> ${GITHUB_ENV}
        export PATH=${GITHUB_WORKSPACE}/install/bin:$PATH
        cd mpi4py-${MPI4PY_VERSION}
        python3 setup.py build --mpicc="mpicc -shared"
        python3 setup.py install --user
    - name: Run MPI4py
      run: |
        export PATH=${GITHUB_WORKSPACE}/install/bin:$PATH
        cd mpi4py-${MPI4PY_VERSION}/test
        mpirun --map-by :OVERSUBSCRIBE -np 3 python3 ./runtests.py
